DROP DATABASE IF EXISTS Jeu_Cartes;
CREATE DATABASE Jeu_Cartes CHARACTER SET 'utf8';
USE Jeu_Cartes;

CREATE TABLE IF NOT EXISTS Cartes (
id_carte SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
titre VARCHAR(40) NOT NULL,
description TEXT,
type VARCHAR(20),
famille VARCHAR(20),
attaque SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
defense SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
rapidite SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
victories SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
FOREIGN KEY (n_deck) REFERENCES Decks(n_deck)
);

CREATE TABLE IF NOT EXISTS Decks (
n_deck SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Versions (
n_version SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
date_impression DATETIME NOT NULL,
rendu SMALLINT UNSIGNED DEFAULT 1 NOT NULL,
tirage SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
cote SMALLINT UNSIGNED NOT NULL,
FOREIGN KEY (id_carte) REFERENCES Cartes(id_carte)
);

CREATE TABLE IF NOT EXISTS Joueurs (
pseudonyme VARCHAR(40) PRIMARY KEY,
nom VARCHAR(40) NOT NULL,
prenom VARCHAR(40) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Possessioncartes (
FOREIGN KEY (id_carte) REFERENCES Cartes(id_carte) PRIMARY KEY,
FOREIGN KEY (pseudonyme) REFERENCES Joueurs(pseudonyme) PRIMARY KEY,
date_possession DATETIME NOT NULL,
methode_possession VARCHAR(20),
date_non_possession DATETIME NOT NULL,
etat SMALLINT UNSIGNED DEFAULT 1 NOT NULL,
);

CREATE TABLE IF NOT EXISTS Possessiondecks (
FOREIGN KEY (n_deck) REFERENCES Decks(n_deck) PRIMARY KEY,
FOREIGN KEY (pseudonyme) REFERENCES Joueurs(pseudonyme) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Parties (
n_partie SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
date DATETIME NOT NULL,
lieu VARCHAR(40),
type VARCHAR(20),
resultat VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS Partiesjouees (
FOREIGN KEY (n_partie) REFERENCES Parties(n_partie) PRIMARY KEY,
FOREIGN KEY (pseudonyme) REFERENCES Joueurs(pseudonyme) PRIMARY KEY,
FOREIGN KEY (n_deck) REFERENCES Decks(n_deck)
);






